version: '3.7'
services:
  nginx:
    build: nginx/.
    volumes:
      - /tmp/data-collector:/var/log/
    ports:
      - "8080:80"
  fluentd:
    build: fluentd/.
    volumes:
      - /tmp/data-collector:/var/log/
    ports:
      - "8888:24224"
 
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    command: --auth

volumes:
  mongodb_data_container:
